### ISSUE TITLE
Nearby selection with PlanningPinToIndex > 0 throws IllegalStateException

### ISSUE THREAD

**Issue by winklerm** [TimefoldAI/timefold-solver-enterprise#73]
**Describe the bug**
When enabling nearby selection with PlanningPinToIndex set to a value > 0, the following IllegalStateException is thrown:

```
java.lang.IllegalStateException: The destinationIterator's size (4) differs from the expected destinationSize (5).
		at ai.timefold.solver.enterprise.core.nearby.common.NearbyDistanceMatrix.addAllDestinations(NearbyDistanceMatrix.java:67)
		at ai.timefold.solver.enterprise.core.nearby.list.ListNearbyDistanceMatrixDemand.lambda$supplyNearbyDistanceMatrix$1(ListNearbyDistanceMatrixDemand.java:72)
		at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1085)
		at ai.timefold.solver.enterprise.core.nearby.list.ListNearbyDistanceMatrixDemand.supplyNearbyDistanceMatrix(ListNearbyDistanceMatrixDemand.java:72)
		at ai.timefold.solver.enterprise.core.nearby.common.AbstractNearbyDistanceMatrixDemand.createExternalizedSupply(AbstractNearbyDistanceMatrixDemand.java:42)
		at ai.timefold.solver.enterprise.core.nearby.common.AbstractNearbyDistanceMatrixDemand.createExternalizedSupply(AbstractNearbyDistanceMatrixDemand.java:24)
		at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.createSupply(VariableListenerSupport.java:78)
		at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.lambda$demand$0(VariableListenerSupport.java:72)
		at java.base/java.util.HashMap.compute(HashMap.java:1324)
		at ai.timefold.solver.core.impl.domain.variable.listener.support.VariableListenerSupport.demand(VariableListenerSupport.java:72)
		at ai.timefold.solver.enterprise.core.nearby.common.AbstractNearbySelector.phaseStarted(AbstractNearbySelector.java:51)
		at ai.timefold.solver.core.impl.phase.event.PhaseLifecycleSupport.firePhaseStarted(PhaseLifecycleSupport.java:21)
		at ai.timefold.solver.core.impl.heuristic.selector.AbstractSelector.phaseStarted(AbstractSelector.java:35)
		at ai.timefold.solver.core.impl.phase.event.PhaseLifecycleSupport.firePhaseStarted(PhaseLifecycleSupport.java:21)
		at ai.timefold.solver.core.impl.heuristic.selector.AbstractSelector.phaseStarted(AbstractSelector.java:35)
		at ai.timefold.solver.core.impl.phase.event.PhaseLifecycleSupport.firePhaseStarted(PhaseLifecycleSupport.java:21)
		at ai.timefold.solver.core.impl.heuristic.selector.AbstractSelector.phaseStarted(AbstractSelector.java:35)
		at ai.timefold.solver.core.impl.heuristic.selector.move.decorator.FilteringMoveSelector.phaseStarted(FilteringMoveSelector.java:35)
		at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.phaseStarted(LocalSearchDecider.java:79)
		at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.phaseStarted(DefaultLocalSearchPhase.java:118)
		at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:59)
		at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:82)
		at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:195)
```

**Expected behavior**
No exception is thrown and solving finishes successfully.

**Actual behavior**
Solving fails with the above exception.

**To Reproduce**
Please run the `ai.timefold.solver.enterprise.core.nearby.NearbySelectionWithPinningTest` from the attached PR.

## Environment

**Timefold Solver Version or Git ref**: 
main branch

**Output of `java -version`:**
```
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (Red_Hat-21.0.2.0.13-1) (build 21.0.2+13)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.2.0.13-1) (build 21.0.2+13, mixed mode, sharing)
```
**Output of `uname -a` or `ver`:**
```
Linux fedora 6.6.13-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 20 18:03:28 UTC 2024 x86_64 GNU/Linux
```
## Additional information

The PR also attempts a fix which works for one of the tests, but the remaining test `solvingOfPinnedIndex1WithNearbySelectionSucceeds` fails on the following exception - if `valueCount` on line 46 is increased to `3`, all tests with PlanningPinIndex > 0 fail on the same:
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "entity" is null

	at ai.timefold.solver.core.impl.domain.entity.descriptor.EntityDescriptor.matchesEntity(EntityDescriptor.java:511)
	at ai.timefold.solver.enterprise.core.nearby.list.AbstractNearbyDestinationSelector.elementRef(AbstractNearbyDestinationSelector.java:81)
	at ai.timefold.solver.enterprise.core.nearby.list.RandomNearbyDestinationIterator.next(RandomNearbyDestinationIterator.java:64)
	at ai.timefold.solver.enterprise.core.nearby.list.RandomNearbyDestinationIterator.next(RandomNearbyDestinationIterator.java:12)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.RandomListChangeIterator.createUpcomingSelection(RandomListChangeIterator.java:45)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.RandomListChangeIterator.createUpcomingSelection(RandomListChangeIterator.java:18)
	at ai.timefold.solver.core.impl.heuristic.selector.common.iterator.UpcomingSelectionIterator.hasNext(UpcomingSelectionIterator.java:27)
	at ai.timefold.solver.core.impl.heuristic.selector.move.composite.UniformRandomUnionMoveIterator.next(UniformRandomUnionMoveIterator.java:44)
	at ai.timefold.solver.core.impl.heuristic.selector.move.composite.UniformRandomUnionMoveIterator.next(UniformRandomUnionMoveIterator.java:12)
	at ai.timefold.solver.core.impl.heuristic.selector.move.decorator.FilteringMoveSelector$JustInTimeFilteringMoveIterator.createUpcomingSelection(FilteringMoveSelector.java:92)
	at ai.timefold.solver.core.impl.heuristic.selector.move.decorator.FilteringMoveSelector$JustInTimeFilteringMoveIterator.createUpcomingSelection(FilteringMoveSelector.java:65)
	at ai.timefold.solver.core.impl.heuristic.selector.common.iterator.UpcomingSelectionIterator.hasNext(UpcomingSelectionIterator.java:27)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.decideNextStep(LocalSearchDecider.java:94)
	at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:82)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:195)
	at ai.timefold.solver.core.impl.testdata.util.PlannerTestUtils.solve(PlannerTestUtils.java:81)
	at ai.timefold.solver.enterprise.core.nearby.NearbySelectionWithPinningTest.runSolvingAndVerifySolutionWithPinIndex(NearbySelectionWithPinningTest.java:55)
	at ai.timefold.solver.enterprise.core.nearby.NearbySelectionWithPinningTest.solvingOfPinnedIndex1WithNearbySelectionSucceeds(NearbySelectionWithPinningTest.java:35)
```

**Comment by winklerm** [comment]
Update: The NPE is caused by the array `destinations` [1] containing a null value.

[1] https://github.com/TimefoldAI/timefold-solver-enterprise/blob/main/core/src/main/java/ai/timefold/solver/enterprise/core/nearby/common/NearbyDistanceMatrix.java#L37

**Comment by winklerm** [comment]
Truncating the `destinations` array leads to `IndexOutOfBounds`:
```
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

	at ai.timefold.solver.enterprise.core.nearby.common.NearbyDistanceMatrix.getDestination(NearbyDistanceMatrix.java:90)
	at ai.timefold.solver.enterprise.core.nearby.list.RandomNearbyDestinationIterator.next(RandomNearbyDestinationIterator.java:63)
	at ai.timefold.solver.enterprise.core.nearby.list.RandomNearbyDestinationIterator.next(RandomNearbyDestinationIterator.java:12)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.RandomListChangeIterator.createUpcomingSelection(RandomListChangeIterator.java:45)
	at ai.timefold.solver.core.impl.heuristic.selector.move.generic.list.RandomListChangeIterator.createUpcomingSelection(RandomListChangeIterator.java:18)
	at ai.timefold.solver.core.impl.heuristic.selector.common.iterator.UpcomingSelectionIterator.hasNext(UpcomingSelectionIterator.java:27)
	at ai.timefold.solver.core.impl.heuristic.selector.move.composite.UniformRandomUnionMoveIterator.next(UniformRandomUnionMoveIterator.java:44)
	at ai.timefold.solver.core.impl.heuristic.selector.move.composite.UniformRandomUnionMoveIterator.next(UniformRandomUnionMoveIterator.java:12)
	at ai.timefold.solver.core.impl.heuristic.selector.move.decorator.FilteringMoveSelector$JustInTimeFilteringMoveIterator.createUpcomingSelection(FilteringMoveSelector.java:92)
	at ai.timefold.solver.core.impl.heuristic.selector.move.decorator.FilteringMoveSelector$JustInTimeFilteringMoveIterator.createUpcomingSelection(FilteringMoveSelector.java:65)
	at ai.timefold.solver.core.impl.heuristic.selector.common.iterator.UpcomingSelectionIterator.hasNext(UpcomingSelectionIterator.java:27)
	at ai.timefold.solver.core.impl.localsearch.decider.LocalSearchDecider.decideNextStep(LocalSearchDecider.java:94)
	at ai.timefold.solver.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:72)
	at ai.timefold.solver.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:82)
	at ai.timefold.solver.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:195)
	at ai.timefold.solver.core.impl.testdata.util.PlannerTestUtils.solve(PlannerTestUtils.java:81)
....
```
